name: github pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
 HUGO_ENV: "production"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.118.2'
          extended: true
      - name: update CNAME
        run: |
          mkdir ./public
          echo patterns.hattori.dev > ./public/CNAME
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public/
